services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-freela
    ports:
      - "8000:8000"
    environment:
      FLASK_ENV: development

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile  
  #   container_name: frontend-freela
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
