FROM python:3.10

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_APP=app.py

ENV FLASK_ENV=development

EXPOSE 8000

CMD ["flask", "run", "--host=0.0.0.0", "--port=8000", "--debug"]